cc_test(
    name = "compiler_drv_test",
    size = "small",
    srcs = ["compiler_drv_test.cpp"],
    copts = ["-Ilib/"],
    deps = ["@com_google_googletest//:gtest_main", "//lib/ir", "//lib/frontend"],
)
